version: '3'
services:
  nestjs:
    build: .
    container_name: nestjs_app
    ports:
      - "3006:3000"
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy
    restart: always

  umami:
    image: ghcr.io/umami-software/umami:postgresql-latest
    ports:
      - '8085:3000'
    environment:
      DATABASE_URL: postgresql://umami:umami@db:5432/umami
      DATABASE_TYPE: postgresql
      APP_SECRET: replace-me-with-a-random-string
    depends_on:
      db:
        condition: service_healthy
    restart: always

  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: umami
      POSTGRES_USER: umami
      POSTGRES_PASSWORD: umami
    volumes:
      - umami-db-data:/var/lib/postgresql/data
    restart: always
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}']
      interval: 5s
      timeout: 5s
      retries: 5

  adminer:
    image: adminer
    ports:
      - '3007:8080'
    depends_on:
      db:
        condition: service_healthy
    restart: always

volumes:
  umami-db-data: